### ISSUE TITLE
hello, it doesn't work , can you give me a guide, i can pay for it

### ISSUE THREAD

**Issue by wx409790282** [x404xx/Turnstile-Solver#4]
thank you very much, gmail  wangxi091@gmail.com

**Comment by x404xx** [comment]
> thank you very much, gmail [wangxi091@gmail.com](mailto:wangxi091@gmail.com)

I'm not sure what's happening; it seems the widget is failing to load.
![Screenshot (20240919-125051)](https://github.com/user-attachments/assets/8370d87f-ca9a-4aa0-9a7a-6eca7f7c0029)

You can try it yourself by saving this HTML file and opening it, or by attempting to change the sitekey.
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Turnstile Challenge</title>
    <script src="https://challenges.cloudflare.com/turnstile/v0/api.js?onload=onloadTurnstileCallback" defer></script>
</head>
<body>
    <div class="cf-turnstile" data-sitekey="0x4AAAAAAAAjq6WYeRDKmebM"></div>
</body>
</html>
```

**Comment by wx409790282** [comment]
thank you very much for you reply. i will take a try
Best wishes for you.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "x404xx/Turnstile-Solver"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月19日(星期四) 中午12:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [x404xx/Turnstile-Solver] hello, it doesn't work , can you give me a guide, i can pay for it (Issue #4)





  
thank you very much, gmail ***@***.***
  
I'm not sure what's happening; it seems the widget is failing to load.
 Screenshot.20240919-125051.png (view on web)
 
You can try it yourself by saving this HTML file and opening it, or by attempting to change the sitekey.
 <!DOCTYPE html&gt; <html lang="en"&gt; <head&gt;     <meta charset="UTF-8"&gt;     <meta name="viewport" content="width=device-width, initial-scale=1.0"&gt;     <title&gt;Turnstile Challenge</title&gt;     <script src="https://challenges.cloudflare.com/turnstile/v0/api.js?onload=onloadTurnstileCallback" defer&gt;</script&gt; </head&gt; <body&gt;     <div class="cf-turnstile" data-sitekey="0x4AAAAAAAAjq6WYeRDKmebM"&gt;</div&gt; </body&gt; </html&gt;

**Comment by wx409790282** [comment]
hello, i hava a new problem.
i try open html files, and get turnstile response, all network go well, but get an error

Uncaught TurnstileError: [Cloudflare Turnstile] Error: 600010.
    at m (api.js?onload=onloadTurnstileCallback:1:10466)
    at O (api.js?onload=onloadTurnstileCallback:1:35845)

have you meet this error before?

**Comment by wx409790282** [comment]
i set the header, and ua,and everything goes well. but i can't see the response or turnstile key in html.
the finnal html i get is :
![微信图片_20240921001953](https://github.com/user-attachments/assets/1961212b-6b71-42cc-aa69-d1fd0c0277ee)
ifram is ok but hidden input value is still null.
no error in console
can you help me about this problem? thank you
